### ISSUE TITLE
jboss-negotiation don't include the license file

### ISSUE THREAD

**Issue by puntogil** [wildfly-security/jboss-negotiation#32]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
Thanks in advance
Regards

**Comment by darranl** [comment]
JBoss Negotiation issues should be raised in the following Jira project with the component set to Negotiation.

https://issues.jboss.org/projects/SECURITY

However I am seeing a lot of issues like this, can you please start a thread on the following mailing list so that everyone knows what is happening - there is no point having an independent discussion for each and every component from the same application server,
